.github: small workflow touchups

diff --git a/.github/workflows/risky.yaml b/.github/workflows/risky.yaml
--- a/.github/workflows/risky.yaml
+++ b/.github/workflows/risky.yaml
@@ -1,5 +1,4 @@
 name: "nixcfg-risky"
-# TODO: this ... still isn't right now though :thinking: :
 concurrency: "nixcfg-risky-${{ inputs.key || github.head_ref || github.ref_name }}"
 on:
   push:
@@ -12,6 +11,7 @@ on:
       git_ref:
         required: true
         type: string
+  workflow_dispatch:
 jobs:
   "builds":
     env:
@@ -31,11 +31,19 @@ jobs:
         ref: ${{ env.GIT_REF }}
     - uses: "DeterminateSystems/determinate-nix-action@main"
     - uses: "DeterminateSystems/magic-nix-cache-action@main"
-    - name: build + cache (jupitertwo)
+    - name: Breakpoint
+      if: github.event_name == 'workflow_dispatch'
+      uses: namespacelabs/breakpoint-action@18b8b1dc6ac651288cfffb20bee1a447632997a1 # v0.0.16
+    - name: build + cache (jupitertwo-cross)
       if: success() || failure()
       run: |
         nix build -L --keep-going \
           .#toplevels.jupitertwo-cross
+    # - name: build + cache (jupitertwo-cross-determinate)
+    #   if: success() || failure()
+    #   run: |
+    #     nix build -L --keep-going \
+    #       .#toplevels.jupitertwo-cross
     - name: build + cache (riscv64 installer)
       if: success() || failure()
       run: |
